### ISSUE TITLE
Revisit some rules regarding react

### ISSUE THREAD

**Issue by satazor** [moxystudio/eslint-config-moxy#16]
- Allow more than one component per file
- Allow stateless components
- Allow arrow functions in props
- Remove `_` prefix in private methods (syntax for private methods will be `#`, see [proposal](https://github.com/tc39/proposal-private-fields))

/cc @andregoncalvesdev 

We should probably align this with #15 in a major release.

**Comment by andregoncalvesdev** [comment]
- Allow more than one component per file
- Allow stateless components
- Allow arrow functions in props

These are currently in master. 

Regarding `Remove _ prefix in private methods (syntax for private methods will be #)`, this is already on stage 3 but only available on babel v7 beta. We should revisit this when babel v7 is published and close this issue.

**Comment by satazor** [comment]
@andregoncalvesdev I think the arrow functions in props is still disallowed, see: https://github.com/moxystudio/eslint-config/blob/85144fd1f56cdb4aef728baf1d0951c823edad5e/rules/react.js#L51

**Comment by satazor** [comment]
Handled in #26
