### ISSUE TITLE
Reminder: after update to ESLint v6, dissalow 'allow require for configs' for nested configs

### ISSUE THREAD

**Issue by threequartersjohn** [moxystudio/eslint-config-moxy#73]
When this package updates to version 6 of ESLint, we must update our override for `.config.js` files to disallow that same override for nested `.config.js` files.

This override can be found [here](https://github.com/moxystudio/eslint-config-moxy/blob/b52e0357793beef484eb2cea2922fea47dd9f15c/addons/es-modules.js#L18). 

The update is probably going to be something like:

```js
'files': './*.config.js'
```

**Comment by satazor** [comment]
Fixed in master.
