### ISSUE TITLE
Disable some react rules in tests

### ISSUE THREAD

**Issue by satazor** [moxystudio/eslint-config-moxy#84]
Disable the following rules in test files: `react/jsx-no-bind`, `react/prop-types`.

Thoughts?

**Comment by acostalima** [comment]
> Disable the following rules in test files: `react/jsx-no-bind`, `react/prop-types`.
> 
> Thoughts?

This is because sometimes it's easier to create inline helper components for testing purposes, right?

**Comment by satazor** [comment]
Exactly.

**Comment by zebateira** [comment]
Sounds good to me 👍
