### ISSUE TITLE
jest global throws 'not defined' error in global mock

### ISSUE THREAD

**Issue by dominguesgm** [moxystudio/eslint-config-moxy#93]
When defining a global mock in `__mocks__/<filename>.js`, using the jest global causes the linter to throw a `jest is not defined` error.

We should modify the `@moxy/eslint-config-jest` package to also override the ESlint config for the files in this directory.

**Comment by satazor** [comment]
@dominguesgm agree. Care to do a PR?

**Comment by dominguesgm** [comment]
Sure thing, I'll take care of it in a bit 👍
